### ISSUE TITLE
Possible deprecation of net/rpc

### ISSUE THREAD

**Issue by cristaloleg** [smallnest/rpcx#27]
[Go proposal](https://github.com/golang/go/issues/16844)
Can deprecation of net/rpc break rpcx?

**Comment by smallnest** [comment]
MY anwser is **NO**.

First, the proposal is freezing net/rpc， net/rpc won't be removed in the offical library. As net/rpc issues mentioned in this proposal comments, rpcx has fixed, for example, TLS and timeout, etc.
From my personal point of view, abandoning the library is not a good action.

Second, if golang team abandon net/rpc not freeze, I will hack the interfaces and implement a similar net/rpc library. It maybe is better solution because I can explore more convenient API for rpcx developement. 

So don't worry about this proposal's affection. I will continue to develop rpcx.

Thanks @cristaloleg
