### ISSUE TITLE
Zero allocation streaming?

### ISSUE THREAD

**Issue by Codebreaker101** [smallnest/rpcx#447]
First off, loving rpcx! 

I'm wondering is it possible to achieve zero allocation streaming?

For example, there's a client service that calculates average age of its users. To do that, it calls a `List` method on the server that returns all of the `Users`. That method would first have to retrieve all of the users, put them into the reply object slice (requiring memory) which would then be sent over the wire to a client that will then store everything in memory. Then, it would iterate over the `Users` slice and calculate the average age. 

What would be nice is if there was a method that can `stream` to the client individual users, memory of which would be garbage collected after each message. Something similar to the `SendMessage` but more integrated in a way that it uses the defined codec to marshal an object and not requiring the need to manually marshal individual object.

**Comment by smallnest** [comment]
It is good feature. I will investigate it, for example, streaming in grpc, and consider how to design and implement.

**Comment by lesismal** [comment]
Sorry, I don't think this is a good idea.
Still taking the calculation of the average age as an example, the server should calculate and return the result instead of returning the original data to the client. If multiple servers hold multiple parts of data, methods such as map/reduce should be considered. If the data is huge, the cost of transmitting the original data itself is high. If the data is not too large, the cost of encoding and decoding is acceptable for an entire transmission. If it is a file, we could download files (using syscall "sendfile", which is zero-copy between kernel and user). In short, should try to avoid the usage like this example, so the implementation seems meaningless

**Comment by smallnest** [comment]
yes, for rpcx, it uses one connection bwtween server and client so huge data affects other calls of clients.

So we have no plan to implement zero allocation streaming currently.
