### ISSUE TITLE
What's the benefit to use QUIC vs TCP, HTTP in RPC area?

### ISSUE THREAD

**Issue by Jeffwan** [smallnest/rpcx#750]
Hi maintainer,

I notice rpcx has supported QUIC protocol. Could I know the benefits to use rpcx over QUIC? Is there benchmark to compare the performance with TCP/HTTP/QUIC/KCP? 

Trying to see how QUIC does in rpc area? We are evaluating whether we should use RPC over QUIC. Thanks for your information!

**Comment by smallnest** [comment]
Actually i have never use quic,because our services are in the same idc.The network still are good even if they are cross regions. So i think tcp is enough.

If your network is not so good, i suggest you to bench mark quic and tcp, using a simple rpcx client/server.

I have not seen an example of quic.
